version: '3.8'
services:
  db:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_DB: parser_db
      POSTGRES_USER: parser
      POSTGRES_PASSWORD: parser_db_password
    ports:
      - 5432:5432
    volumes:
      - ./database/data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - 80:80
    depends_on:
      - db
    env_file: .env

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db-data:
